# generated by datamodel-codegen:
#   filename:  board-document.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr


class Axes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    show_arrows: bool = Field(..., alias="showArrows")
    show_labels: bool = Field(..., alias="showLabels")
    show_x_axis: bool = Field(..., alias="showXAxis")
    show_y_axis: bool = Field(..., alias="showYAxis")
    x_label: str = Field(..., alias="xLabel", max_length=32)
    y_label: str = Field(..., alias="yLabel", max_length=32)


class CoordinateViewport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    equal_scale: bool = Field(..., alias="equalScale")
    x_max: float = Field(..., alias="xMax")
    x_min: float = Field(..., alias="xMin")
    y_max: float = Field(..., alias="yMax")
    y_min: float = Field(..., alias="yMin")


class Grid(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    automatic_step: bool = Field(..., alias="automaticStep")
    major_visible: bool = Field(..., alias="majorVisible")
    minor_visible: bool = Field(..., alias="minorVisible")
    visible: bool
    x_step: float | None = Field(..., alias="xStep")
    y_step: float | None = Field(..., alias="yStep")


class Position(Enum):
    top_left = "top-left"
    top_right = "top-right"
    bottom_left = "bottom-left"
    bottom_right = "bottom-right"


class Legend(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    position: Position
    visible: bool


class Size(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., ge=100.0, le=16384.0)
    width: float = Field(..., ge=120.0, le=16384.0)


class IntrinsicSize(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0, le=16384.0)
    width: float = Field(..., gt=0.0, le=16384.0)


class MimeType(Enum):
    image_png = "image/png"
    image_jpeg = "image/jpeg"
    image_svg_xml = "image/svg+xml"
    image_gif = "image/gif"


class Size5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0, le=16384.0)
    width: float = Field(..., gt=0.0, le=16384.0)


Identifier = RootModel[str]


class LineStyle(Enum):
    dashed = "dashed"
    solid = "solid"


class StrokeStyle(Enum):
    thin = "thin"
    thick = "thick"
    dashed = "dashed"
    dash_dot = "dash-dot"
    wavy = "wavy"
    hand_pencil = "hand-pencil"
    hand_pen = "hand-pen"
    marker = "marker"


class ObjectStyle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fill: str | None = Field(..., max_length=256)
    opacity: float = Field(..., ge=0.0, le=1.0)
    stroke: str | None = Field(..., max_length=256)
    stroke_width: float = Field(..., alias="strokeWidth", ge=0.0)
    stroke_style: StrokeStyle | None = Field(None, alias="strokeStyle")


MaxExpression = RootModel[str]


MinExpression = RootModel[str]


class Domain(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_expression: MaxExpression | None = Field(..., alias="maxExpression")
    min_expression: MinExpression | None = Field(..., alias="minExpression")


class Range(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_expression: str = Field(..., alias="maxExpression", max_length=2000, min_length=1)
    min_expression: str = Field(..., alias="minExpression", max_length=2000, min_length=1)


class PlotParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    max: float | None
    min: float | None
    name: str = Field(..., max_length=32, min_length=1)
    step: float | None
    value: float


class LineStyle3(Enum):
    solid = "solid"
    dashed = "dashed"
    dash_dot = "dash-dot"


class PlotSeriesStyle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    line_style: LineStyle3 = Field(..., alias="lineStyle")
    opacity: float = Field(..., ge=0.0, le=1.0)
    stroke: str = Field(..., max_length=256, min_length=1)
    stroke_width: float = Field(..., alias="strokeWidth", ge=0.25, le=32.0)


class PositiveVec2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float = Field(..., gt=0.0)
    y: float = Field(..., gt=0.0)


class Size2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0)
    width: float = Field(..., gt=0.0)


class SvgViewBox(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0, le=1000000.0)
    width: float = Field(..., gt=0.0, le=1000000.0)
    x: float
    y: float


class HiddenEdgePolicy(Enum):
    dashed = "dashed"
    hidden = "hidden"


class Kind(Enum):
    oblique = "oblique"
    orthographic = "orthographic"
    perspective = "perspective"


class Solid3DDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    edge_length: float = Field(..., alias="edgeLength", gt=0.0)
    kind: Literal["cube"]


class Solid3DDefinition13(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    edge_length: float = Field(..., alias="edgeLength", gt=0.0)
    kind: Literal["tetrahedron"]


class Solid3DDefinition16(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0)
    kind: Literal["cylinder"]
    radius: float = Field(..., gt=0.0)


class Solid3DDefinition17(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0)
    kind: Literal["cone"]
    radius: float = Field(..., gt=0.0)


class Solid3DDefinition18(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bottom_radius: float = Field(..., alias="bottomRadius", gt=0.0)
    height: float = Field(..., gt=0.0)
    kind: Literal["truncated-cone"]
    top_radius: float = Field(..., alias="topRadius", gt=0.0)


class Solid3DDefinition19(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["sphere"]
    radius: float = Field(..., gt=0.0)


class AlgorithmVersion(Enum):
    analytic_plane_1 = "analytic-plane/1"
    polyhedron_plane_1 = "polyhedron-plane/1"


class Solid3DSectionDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    algorithm_version: AlgorithmVersion = Field(..., alias="algorithmVersion")
    id: Identifier
    point_ids: list[Identifier] = Field(..., alias="pointIds", max_length=3, min_length=3)
    visible: bool


class Solid3DSource4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["text-template"]
    template_id: str = Field(..., alias="templateId", max_length=128, min_length=1)


class Solid3DSource5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["smart-ink"]
    recognizer_version: str = Field(..., alias="recognizerVersion", max_length=128, min_length=1)


class Solid3DSource6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    import_id: Identifier = Field(..., alias="importId")
    kind: Literal["geometryos"]


Solid3DSource = RootModel[Solid3DSource4 | Solid3DSource5 | Solid3DSource6]


class SolidPointAnchor5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["vertex"]
    vertex_id: Identifier = Field(..., alias="vertexId")


class SolidPointAnchor6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    edge_id: Identifier = Field(..., alias="edgeId")
    kind: Literal["edge"]
    parameter: float = Field(..., ge=0.0, le=1.0)


class SolidPointAnchor8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["analytic-surface"]
    parameters: list[float] = Field(..., max_length=8)
    surface_id: Identifier = Field(..., alias="surfaceId")


class ExactValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    denominator: int = Field(..., ge=1)
    kind: Literal["rational"]
    numerator: int


class ExactValue6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    coefficient_denominator: int = Field(..., alias="coefficientDenominator", ge=1)
    coefficient_numerator: int = Field(..., alias="coefficientNumerator")
    kind: Literal["radical"]
    radicand: int = Field(..., ge=0)


class ExactValue7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["decimal"]
    value: float


ExactValue4 = RootModel[ExactValue | ExactValue6 | ExactValue7]


class SolidConstructionAction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    face_id: Identifier = Field(..., alias="faceId")
    kind: Literal["select-face"]


class SolidConstructionAction7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    edge_id: Identifier = Field(..., alias="edgeId")
    kind: Literal["add-derived-point"]
    parameter: float


class SolidConstructionAction8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    face_id: Identifier = Field(..., alias="faceId")
    from_point_id: Identifier = Field(..., alias="fromPointId")
    kind: Literal["add-trace-segment"]
    to_point_id: Identifier = Field(..., alias="toPointId")


class SolidConstructionAction9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["close-contour"]
    ordered_point_ids: list[Identifier] = Field(
        ..., alias="orderedPointIds", max_length=32, min_length=3
    )


SolidConstructionAction5 = RootModel[
    SolidConstructionAction
    | SolidConstructionAction7
    | SolidConstructionAction8
    | SolidConstructionAction9
]


class SolidElementRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    kind: Literal["vertex"]


class SolidElementRef8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    kind: Literal["edge"]


class SolidElementRef9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    kind: Literal["face"]


class SolidElementRef10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    kind: Literal["point"]


class SolidElementRef11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    kind: Literal["section-segment"]


SolidElementRef6 = RootModel[
    SolidElementRef | SolidElementRef8 | SolidElementRef9 | SolidElementRef10 | SolidElementRef11
]


class Phase(Enum):
    intro = "intro"
    prediction = "prediction"
    construction = "construction"
    reasoning = "reasoning"
    measurement = "measurement"
    reflection = "reflection"
    completed = "completed"


class SolidLearningAttemptAction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["set-phase"]
    phase: Phase


class Confidence(Enum):
    confident = "confident"
    unsure = "unsure"
    stuck = "stuck"


ParallelSidePair = RootModel[list[Identifier]]


Score = RootModel[float]


VertexCount = RootModel[int]


class Prediction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    confidence: Confidence
    edge_ids: list[Identifier] = Field(..., alias="edgeIds", max_length=64)
    parallel_side_pairs: list[ParallelSidePair] = Field(
        ..., alias="parallelSidePairs", max_length=32
    )
    polygon_kind: str = Field(..., alias="polygonKind", max_length=64)
    score: Score | None
    submitted: bool
    vertex_count: VertexCount | None = Field(..., alias="vertexCount")


class SolidLearningAttemptAction13(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["submit-prediction"]
    prediction: Prediction


class Step(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accepted: bool
    premise_ids: list[Identifier] = Field(..., alias="premiseIds", max_length=16)
    rule_id: Identifier = Field(..., alias="ruleId")
    statement_id: Identifier = Field(..., alias="statementId")


class SolidLearningAttemptAction15(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["add-reasoning"]
    step: Step


class Answer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    correct: bool
    formula_id: Identifier | None = Field(..., alias="formulaId")
    parsed: ExactValue4 | None
    raw: str = Field(..., max_length=256)
    task_id: Identifier = Field(..., alias="taskId")
    timestamp: AwareDatetime
    unit: str = Field(..., max_length=32)


class SolidLearningAttemptAction16(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    answer: Answer
    kind: Literal["submit-answer"]


class Level(Enum):
    int_1 = 1
    int_2 = 2
    int_3 = 3


class Hint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    ladder_id: Identifier = Field(..., alias="ladderId")
    level: Level
    related_element: SolidElementRef6 | None = Field(..., alias="relatedElement")
    timestamp: AwareDatetime


class SolidLearningAttemptAction17(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    hint: Hint
    kind: Literal["use-hint"]


class Checkpoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: float = Field(..., ge=0.0)
    parameter: float
    perimeter: float = Field(..., ge=0.0)
    timestamp: AwareDatetime
    vertex_count: int = Field(..., alias="vertexCount", ge=0)


class SolidLearningAttemptAction19(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    checkpoint: Checkpoint
    kind: Literal["add-checkpoint"]


class SolidLearningAttemptAction20(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    answer: str = Field(..., max_length=512)
    item_id: Identifier = Field(..., alias="itemId")
    kind: Literal["answer-quiz"]


class SolidLearningDiagnosticCode(Enum):
    points_on_different_faces = "points-on-different-faces"
    missed_edge_intersection = "missed-edge-intersection"
    wrong_contour_order = "wrong-contour-order"
    self_intersection = "self-intersection"
    point_outside_edge = "point-outside-edge"
    segment_outside_section_plane = "segment-outside-section-plane"
    duplicate_or_collinear_seeds = "duplicate-or-collinear-seeds"
    invalid_proof_premises = "invalid-proof-premises"
    incorrect_formula = "incorrect-formula"
    incorrect_unit = "incorrect-unit"


class Diagnostic(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: SolidLearningDiagnosticCode
    element: SolidElementRef6 | None
    id: Identifier
    message: str = Field(..., max_length=1000)
    timestamp: AwareDatetime


class Hint3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    ladder_id: Identifier = Field(..., alias="ladderId")
    level: Level
    related_element: SolidElementRef6 | None = Field(..., alias="relatedElement")
    timestamp: AwareDatetime


class Mode(Enum):
    guided = "guided"
    assessment = "assessment"
    teacher_demo = "teacher-demo"


class Prediction3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    confidence: Confidence
    edge_ids: list[Identifier] = Field(..., alias="edgeIds", max_length=64)
    parallel_side_pairs: list[ParallelSidePair] = Field(
        ..., alias="parallelSidePairs", max_length=32
    )
    polygon_kind: str = Field(..., alias="polygonKind", max_length=64)
    score: Score | None
    submitted: bool
    vertex_count: VertexCount | None = Field(..., alias="vertexCount")


class ReasoningItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accepted: bool
    premise_ids: list[Identifier] = Field(..., alias="premiseIds", max_length=16)
    rule_id: Identifier = Field(..., alias="ruleId")
    statement_id: Identifier = Field(..., alias="statementId")


class Result(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    completed: bool
    construction_accuracy: float = Field(..., alias="constructionAccuracy", ge=0.0, le=1.0)
    maximum_hint_level: int = Field(..., alias="maximumHintLevel", ge=0, le=3)
    measurement_accuracy: float = Field(..., alias="measurementAccuracy", ge=0.0, le=1.0)
    prediction_score: float = Field(..., alias="predictionScore", ge=0.0, le=1.0)
    quiz_score: float = Field(..., alias="quizScore", ge=0.0, le=1.0)
    reasoning_accuracy: float = Field(..., alias="reasoningAccuracy", ge=0.0, le=1.0)
    skill_scores: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        float,
    ] = Field(..., alias="skillScores")


class UserObjectSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["user"]


class Vec2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float
    y: float


class Vec3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float
    y: float
    z: float


class Viewport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    offset: Vec2
    zoom: float = Field(..., gt=0.0)


class VisualStyleOverride(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fill: str | None = Field(None, max_length=256)
    opacity: float | None = Field(None, ge=0.0, le=1.0)
    stroke: str | None = Field(None, max_length=256)
    stroke_width: float | None = Field(None, alias="strokeWidth", ge=0.0)


class GeometryOsObjectSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    gir_entity_id: str = Field(..., alias="girEntityId", max_length=256, min_length=1)
    gir_entity_type: str = Field(..., alias="girEntityType", max_length=128, min_length=1)
    import_id: Identifier = Field(..., alias="importId")
    kind: Literal["geometryos"]


class LineObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.line"]
    end: Vec2
    line_style: LineStyle | None = Field(None, alias="lineStyle")


class ExplicitPlotSeries(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    domain: Domain
    expression: str = Field(..., max_length=2000, min_length=1)
    id: Identifier
    kind: Literal["explicit"]
    name: str = Field(..., max_length=128, min_length=1)
    style: PlotSeriesStyle
    visible: bool


class ParametricPlotSeries(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    closed: bool
    id: Identifier
    kind: Literal["parametric"]
    name: str = Field(..., max_length=128, min_length=1)
    parameter_name: Literal["t"] = Field(..., alias="parameterName")
    range: Range
    style: PlotSeriesStyle
    visible: bool
    x_expression: str = Field(..., alias="xExpression", max_length=2000, min_length=1)
    y_expression: str = Field(..., alias="yExpression", max_length=2000, min_length=1)


class RelationPlotSeries(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expression: str = Field(..., max_length=2000, min_length=1)
    fill_opacity: float = Field(..., alias="fillOpacity", ge=0.0, le=1.0)
    id: Identifier
    kind: Literal["relation"]
    name: str = Field(..., max_length=128, min_length=1)
    style: PlotSeriesStyle
    visible: bool


PlotSeries = RootModel[ExplicitPlotSeries | ParametricPlotSeries | RelationPlotSeries]


class CubicBezierSegment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    control1: Vec2
    control2: Vec2
    end: Vec2
    start: Vec2


class VectorInkSample(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    point: Vec2
    pressure: float = Field(..., ge=0.0, le=1.0)
    timestamp_ms: float = Field(..., alias="timestampMs", ge=0.0)


class RectangleObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.rectangle"]
    size: Size2


class SvgObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["svg-import.svg"]
    sanitized_svg: str = Field(..., alias="sanitizedSvg", max_length=524288, min_length=1)
    sanitizer_policy_version: Literal["tutorboard.svg-sanitizer/1"] = Field(
        ..., alias="sanitizerPolicyVersion"
    )
    size: Size5
    view_box: SvgViewBox = Field(..., alias="viewBox")


class Solid3DBoardProjection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    hidden_edge_policy: HiddenEdgePolicy = Field(..., alias="hiddenEdgePolicy")
    kind: Kind
    matrix: list[float] = Field(..., max_length=16, min_length=6)
    origin: Vec2
    viewport_scale: float = Field(..., alias="viewportScale", gt=0.0)


class Solid3DDefinition12(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["cuboid"]
    size: Vec3


class Solid3DDefinition14(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base: list[Vec2] = Field(..., max_length=256, min_length=3)
    height: float = Field(..., gt=0.0)
    kind: Literal["prism"]


class Solid3DDefinition15(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    apex: Vec3
    base: list[Vec2] = Field(..., max_length=256, min_length=3)
    kind: Literal["pyramid"]


Solid3DDefinition10 = RootModel[
    Solid3DDefinition
    | Solid3DDefinition12
    | Solid3DDefinition13
    | Solid3DDefinition14
    | Solid3DDefinition15
    | Solid3DDefinition16
    | Solid3DDefinition17
    | Solid3DDefinition18
    | Solid3DDefinition19
]


class SolidPointAnchor7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    face_id: Identifier = Field(..., alias="faceId")
    kind: Literal["face"]
    local_coordinates: Vec2 = Field(..., alias="localCoordinates")


SolidPointAnchor = RootModel[
    SolidPointAnchor5 | SolidPointAnchor6 | SolidPointAnchor7 | SolidPointAnchor8
]


class SolidConstructionTraceEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accepted: bool
    action: SolidConstructionAction5
    diagnostic_code: SolidLearningDiagnosticCode | None = Field(..., alias="diagnosticCode")
    explanation: str = Field(..., max_length=1000)
    id: Identifier
    timestamp: AwareDatetime


class SolidLearningAttemptAction14(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entry: SolidConstructionTraceEntry
    kind: Literal["construction-step"]


class SolidLearningAttemptAction18(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    diagnostic: Diagnostic
    kind: Literal["add-diagnostic"]


class Construction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    completed: bool
    trace: list[SolidConstructionTraceEntry] = Field(..., max_length=128)


class Solid3DLearningAttempt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    answers: list[Answer] = Field(..., max_length=128)
    checkpoints: list[Checkpoint] = Field(..., max_length=32)
    construction: Construction
    diagnostics: list[Diagnostic] = Field(..., max_length=64)
    hints: list[Hint3] = Field(..., max_length=24)
    id: Identifier
    mode: Mode
    phase: Phase
    prediction: Prediction3 | None
    quiz_answers: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        str,
    ] = Field(..., alias="quizAnswers")
    reasoning: list[ReasoningItem] = Field(..., max_length=128)
    result: Result | None
    revision: int = Field(..., ge=0)
    scenario_id: Identifier = Field(..., alias="scenarioId")
    scenario_version: str = Field(..., alias="scenarioVersion", max_length=32, min_length=1)
    schema_version: Literal["1.0"] = Field(..., alias="schemaVersion")
    solid_id: Identifier = Field(..., alias="solidId")
    started_at: AwareDatetime = Field(..., alias="startedAt")
    updated_at: AwareDatetime = Field(..., alias="updatedAt")


class TextObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.text"]
    text: str = Field(..., max_length=100000)


class Transform2D(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rotation: float
    scale: PositiveVec2
    translation: Vec2


class VisualOverride(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rotation: float
    scale: PositiveVec2
    style: VisualStyleOverride | None = None
    translation: Vec2


class BoardGroup(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    locked: bool
    object_ids: list[Identifier] = Field(..., alias="objectIds", min_length=1)
    transform: Transform2D


class CoordinatePlotDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    axes: Axes
    coordinate_viewport: CoordinateViewport = Field(..., alias="coordinateViewport")
    expression_language: Literal["tutorboard-expression/1"] = Field(..., alias="expressionLanguage")
    grid: Grid
    legend: Legend
    parameters: list[PlotParameter] = Field(..., max_length=32)
    series: list[PlotSeries] = Field(..., max_length=32)
    size: Size


class CoordinatePlotObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["math.coordinate-plot"]
    definition: CoordinatePlotDefinition


class EllipseObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.ellipse"]
    radius: PositiveVec2


class EmbeddedImageObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["image.embedded"]
    content_sha256: str = Field(..., alias="contentSha256", pattern="^[a-f0-9]{64}$")
    data_url: str = Field(
        ...,
        alias="dataUrl",
        max_length=12582912,
        min_length=1,
        pattern="^data:image/(?:png|jpeg|gif|svg\\+xml);base64,[A-Za-z0-9+/=]+$",
    )
    file_name: str = Field(..., alias="fileName", max_length=256, min_length=1)
    intrinsic_size: IntrinsicSize = Field(..., alias="intrinsicSize")
    mime_type: MimeType = Field(..., alias="mimeType")
    size: Size5


class GeometryImportRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    board_object_ids: list[Identifier] = Field(..., alias="boardObjectIds", min_length=1)
    canonical_gir: Any = Field(..., alias="canonicalGir")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    geometry_os_api_version: Literal["1.0.0"] = Field(..., alias="geometryOsApiVersion")
    gir_schema_version: Literal["0.2.0"] = Field(..., alias="girSchemaVersion")
    id: Identifier
    mapping: dict[str, list[Identifier]]
    prompt: str = Field(..., max_length=100000)
    raw_response: Any = Field(..., alias="rawResponse")
    request_id: str | None = Field(..., alias="requestId", pattern="^[A-Za-z0-9._:-]{1,220}$")
    root_group_id: Identifier = Field(..., alias="rootGroupId")
    visual_overrides: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        VisualOverride,
    ] = Field(..., alias="visualOverrides")
    visual_transform: Transform2D = Field(..., alias="visualTransform")


class VectorInkData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    centerline: list[CubicBezierSegment] = Field(..., max_length=100000, min_length=1)
    closed: bool
    samples: list[VectorInkSample] = Field(..., max_length=100000, min_length=2)
    version: Literal["1.0"]


class Solid3DPoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    anchor: SolidPointAnchor
    id: Identifier
    label: str = Field(..., max_length=32, min_length=1)
    position: Vec3


class Solid3DRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    board_object_ids: list[Identifier] = Field(..., alias="boardObjectIds", max_length=5000)
    definition: Solid3DDefinition10
    id: Identifier
    points: list[Solid3DPoint] = Field(..., max_length=32)
    projection: Solid3DBoardProjection
    root_group_id: Identifier = Field(..., alias="rootGroupId")
    schema_version: Literal["1.0"] = Field(..., alias="schemaVersion")
    sections: list[Solid3DSectionDefinition] = Field(..., max_length=8)
    source: Solid3DSource


class SolidLearningAttemptAction21(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["restore"]
    snapshot: Solid3DLearningAttempt


SolidLearningAttemptAction11 = RootModel[
    SolidLearningAttemptAction
    | SolidLearningAttemptAction13
    | SolidLearningAttemptAction14
    | SolidLearningAttemptAction15
    | SolidLearningAttemptAction16
    | SolidLearningAttemptAction17
    | SolidLearningAttemptAction18
    | SolidLearningAttemptAction19
    | SolidLearningAttemptAction20
    | SolidLearningAttemptAction21
]


class PenStrokeObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.pen-stroke"]
    ink: VectorInkData
    points: list[Vec2] = Field(..., max_length=100000, min_length=2)


BoardObject = RootModel[
    PenStrokeObject
    | LineObject
    | RectangleObject
    | EllipseObject
    | TextObject
    | EmbeddedImageObject
    | SvgObject
    | CoordinatePlotObject
]


class BoardDocument(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    created_at: AwareDatetime = Field(..., alias="createdAt")
    geometry_imports: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        GeometryImportRecord,
    ] = Field(..., alias="geometryImports")
    groups: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        BoardGroup,
    ]
    id: Identifier
    objects: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        BoardObject,
    ]
    order: list[Identifier]
    schema_version: Literal["1.4"] = Field(..., alias="schemaVersion")
    solid_learning_attempts: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        Solid3DLearningAttempt,
    ] = Field(..., alias="solidLearningAttempts")
    solid_models: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        Solid3DRecord,
    ] = Field(..., alias="solidModels")
    title: str = Field(..., max_length=256, min_length=1)
    updated_at: AwareDatetime = Field(..., alias="updatedAt")
    viewport: Viewport


BoardDocument14 = RootModel[BoardDocument]
