# generated by datamodel-codegen:
#   filename:  board-geometry-import.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class GeometryOs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    api_version: Literal["1.0.0"] = Field(..., alias="apiVersion")
    gir_schema_version: Literal["0.2.0"] = Field(..., alias="girSchemaVersion")
    gir_sha256: str = Field(..., alias="girSha256", pattern="^[a-f0-9]{64}$")
    layout_document_version: Literal["0.1.0"] = Field(..., alias="layoutDocumentVersion")
    layout_sha256: str = Field(..., alias="layoutSha256", pattern="^[a-f0-9]{64}$")
    request_id: str = Field(
        ..., alias="requestId", max_length=220, min_length=1, pattern="^[A-Za-z0-9._:-]+$"
    )
    service_version: str = Field(..., alias="serviceVersion", pattern="^0\\.[0-9]+\\.[0-9]+$")


Identifier = RootModel[str]


class BoardGeometryImport11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_revision: int = Field(..., alias="baseRevision", ge=0)
    command_id: Identifier = Field(..., alias="commandId")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    document_id: Identifier = Field(..., alias="documentId")
    geometry_os: GeometryOs = Field(..., alias="geometryOs")
    import_id: Identifier = Field(..., alias="importId")
    prompt: str = Field(..., max_length=100000, min_length=1)
    schema_version: Literal["1.2"] = Field(..., alias="schemaVersion")
