# generated by datamodel-codegen:
#   filename:  board-document.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr

Identifier = RootModel[str]


class LineStyle(Enum):
    dashed = "dashed"
    solid = "solid"


class ObjectStyle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fill: str | None = Field(..., max_length=256)
    opacity: float = Field(..., ge=0.0, le=1.0)
    stroke: str | None = Field(..., max_length=256)
    stroke_width: float = Field(..., alias="strokeWidth", ge=0.0)


class PositiveVec2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float = Field(..., gt=0.0)
    y: float = Field(..., gt=0.0)


class Size2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0)
    width: float = Field(..., gt=0.0)


class Size(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0, le=16384.0)
    width: float = Field(..., gt=0.0, le=16384.0)


class SvgViewBox(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0, le=1000000.0)
    width: float = Field(..., gt=0.0, le=1000000.0)
    x: float
    y: float


class UserObjectSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["user"]


class Vec2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float
    y: float


class Viewport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    offset: Vec2
    zoom: float = Field(..., gt=0.0)


class VisualStyleOverride(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fill: str | None = Field(None, max_length=256)
    opacity: float | None = Field(None, ge=0.0, le=1.0)
    stroke: str | None = Field(None, max_length=256)
    stroke_width: float | None = Field(None, alias="strokeWidth", ge=0.0)


class GeometryOsObjectSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    gir_entity_id: str = Field(..., alias="girEntityId", max_length=256, min_length=1)
    gir_entity_type: str = Field(..., alias="girEntityType", max_length=128, min_length=1)
    import_id: Identifier = Field(..., alias="importId")
    kind: Literal["geometryos"]


class LineObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.line"]
    end: Vec2
    line_style: LineStyle | None = Field(None, alias="lineStyle")


class PenStrokeObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.pen-stroke"]
    points: list[Vec2] = Field(..., max_length=100000, min_length=2)


class RectangleObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.rectangle"]
    size: Size2


class SvgObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["svg-import.svg"]
    sanitized_svg: str = Field(..., alias="sanitizedSvg", max_length=524288, min_length=1)
    sanitizer_policy_version: Literal["tutorboard.svg-sanitizer/1"] = Field(
        ..., alias="sanitizerPolicyVersion"
    )
    size: Size
    view_box: SvgViewBox = Field(..., alias="viewBox")


class TextObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.text"]
    text: str = Field(..., max_length=100000)


class Transform2D(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rotation: float
    scale: PositiveVec2
    translation: Vec2


class VisualOverride(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rotation: float
    scale: PositiveVec2
    style: VisualStyleOverride | None = None
    translation: Vec2


class BoardGroup(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    locked: bool
    object_ids: list[Identifier] = Field(..., alias="objectIds", min_length=1)
    transform: Transform2D


class EllipseObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.ellipse"]
    radius: PositiveVec2


class GeometryImportRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    board_object_ids: list[Identifier] = Field(..., alias="boardObjectIds", min_length=1)
    canonical_gir: Any = Field(..., alias="canonicalGir")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    geometry_os_api_version: Literal["1.0.0"] = Field(..., alias="geometryOsApiVersion")
    gir_schema_version: Literal["0.2.0"] = Field(..., alias="girSchemaVersion")
    id: Identifier
    mapping: dict[str, list[Identifier]]
    prompt: str = Field(..., max_length=100000)
    raw_response: Any = Field(..., alias="rawResponse")
    request_id: str | None = Field(..., alias="requestId", pattern="^[A-Za-z0-9._:-]{1,220}$")
    root_group_id: Identifier = Field(..., alias="rootGroupId")
    visual_overrides: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        VisualOverride,
    ] = Field(..., alias="visualOverrides")
    visual_transform: Transform2D = Field(..., alias="visualTransform")


BoardObject = RootModel[
    PenStrokeObject | LineObject | RectangleObject | EllipseObject | TextObject | SvgObject
]


class BoardDocument(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    created_at: AwareDatetime = Field(..., alias="createdAt")
    geometry_imports: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        GeometryImportRecord,
    ] = Field(..., alias="geometryImports")
    groups: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        BoardGroup,
    ]
    id: Identifier
    objects: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        BoardObject,
    ]
    order: list[Identifier]
    schema_version: Literal["1.0"] = Field(..., alias="schemaVersion")
    title: str = Field(..., max_length=256, min_length=1)
    updated_at: AwareDatetime = Field(..., alias="updatedAt")
    viewport: Viewport


BoardDocument10 = RootModel[BoardDocument]
