# generated by datamodel-codegen:
#   filename:  board-command-envelope.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr


class Axes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    show_arrows: bool = Field(..., alias="showArrows")
    show_labels: bool = Field(..., alias="showLabels")
    show_x_axis: bool = Field(..., alias="showXAxis")
    show_y_axis: bool = Field(..., alias="showYAxis")
    x_label: str = Field(..., alias="xLabel", max_length=32)
    y_label: str = Field(..., alias="yLabel", max_length=32)


class CoordinateViewport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    equal_scale: bool = Field(..., alias="equalScale")
    x_max: float = Field(..., alias="xMax")
    x_min: float = Field(..., alias="xMin")
    y_max: float = Field(..., alias="yMax")
    y_min: float = Field(..., alias="yMin")


class Grid(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    automatic_step: bool = Field(..., alias="automaticStep")
    major_visible: bool = Field(..., alias="majorVisible")
    minor_visible: bool = Field(..., alias="minorVisible")
    visible: bool
    x_step: float | None = Field(..., alias="xStep")
    y_step: float | None = Field(..., alias="yStep")


class Position(Enum):
    top_left = "top-left"
    top_right = "top-right"
    bottom_left = "bottom-left"
    bottom_right = "bottom-right"


class Legend(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    position: Position
    visible: bool


class Size(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., ge=100.0, le=16384.0)
    width: float = Field(..., ge=120.0, le=16384.0)


class IntrinsicSize(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0, le=16384.0)
    width: float = Field(..., gt=0.0, le=16384.0)


class MimeType(Enum):
    image_png = "image/png"
    image_jpeg = "image/jpeg"
    image_svg_xml = "image/svg+xml"
    image_gif = "image/gif"


class Size1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0, le=16384.0)
    width: float = Field(..., gt=0.0, le=16384.0)


Identifier = RootModel[str]


class LineStyle(Enum):
    dashed = "dashed"
    solid = "solid"


class ObjectStyle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fill: str | None = Field(..., max_length=256)
    opacity: float = Field(..., ge=0.0, le=1.0)
    stroke: str | None = Field(..., max_length=256)
    stroke_width: float = Field(..., alias="strokeWidth", ge=0.0)


MaxExpression = RootModel[str]


MinExpression = RootModel[str]


class Domain(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_expression: MaxExpression | None = Field(..., alias="maxExpression")
    min_expression: MinExpression | None = Field(..., alias="minExpression")


class Range(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_expression: str = Field(..., alias="maxExpression", max_length=2000, min_length=1)
    min_expression: str = Field(..., alias="minExpression", max_length=2000, min_length=1)


class PlotParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    max: float | None
    min: float | None
    name: str = Field(..., max_length=32, min_length=1)
    step: float | None
    value: float


class LineStyle1(Enum):
    solid = "solid"
    dashed = "dashed"
    dash_dot = "dash-dot"


class PlotSeriesStyle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    line_style: LineStyle1 = Field(..., alias="lineStyle")
    opacity: float = Field(..., ge=0.0, le=1.0)
    stroke: str = Field(..., max_length=256, min_length=1)
    stroke_width: float = Field(..., alias="strokeWidth", ge=0.25, le=32.0)


class PositiveVec2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float = Field(..., gt=0.0)
    y: float = Field(..., gt=0.0)


class Size2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0)
    width: float = Field(..., gt=0.0)


class SvgViewBox(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: float = Field(..., gt=0.0, le=1000000.0)
    width: float = Field(..., gt=0.0, le=1000000.0)
    x: float
    y: float


class UserObjectSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["user"]


class Vec2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: float
    y: float


class Viewport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    offset: Vec2
    zoom: float = Field(..., gt=0.0)


class VisualStyleOverride(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fill: str | None = Field(None, max_length=256)
    opacity: float | None = Field(None, ge=0.0, le=1.0)
    stroke: str | None = Field(None, max_length=256)
    stroke_width: float | None = Field(None, alias="strokeWidth", ge=0.0)


class CutContentCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.clipboard.cut"]
    timestamp: AwareDatetime
    geometry_import_ids: list[Identifier] = Field(..., alias="geometryImportIds")
    group_ids: list[Identifier] = Field(..., alias="groupIds")
    object_ids: list[Identifier] = Field(..., alias="objectIds")


class DeleteObjectsCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.objects.delete"]
    timestamp: AwareDatetime
    object_ids: list[Identifier] = Field(..., alias="objectIds", min_length=1)


class MoveGroupCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.groups.move"]
    timestamp: AwareDatetime
    delta: Vec2
    group_id: Identifier = Field(..., alias="groupId")


class MoveObjectsCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.objects.move"]
    timestamp: AwareDatetime
    delta: Vec2
    object_ids: list[Identifier] = Field(..., alias="objectIds", min_length=1)


class MoveSelectionCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.selection.move"]
    timestamp: AwareDatetime
    delta: Vec2
    group_ids: list[Identifier] = Field(..., alias="groupIds")
    object_ids: list[Identifier] = Field(..., alias="objectIds")


class OffsetGeometryLabelCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.geometry.label-offset"]
    timestamp: AwareDatetime
    delta: Vec2
    import_id: Identifier = Field(..., alias="importId")
    object_id: Identifier = Field(..., alias="objectId")


class RemoveGroupsCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.groups.remove"]
    timestamp: AwareDatetime
    group_ids: list[Identifier] = Field(..., alias="groupIds", min_length=1)


class RenameDocumentCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.document.rename"]
    timestamp: AwareDatetime
    title: str = Field(..., max_length=256, min_length=1)


class Mode(Enum):
    back = "back"
    backward = "backward"
    forward = "forward"
    front = "front"


class ReorderLayersCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.layers.reorder"]
    timestamp: AwareDatetime
    mode: Mode
    object_ids: list[Identifier] = Field(..., alias="objectIds", min_length=1)


class SetGeometryVisualStyleCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.geometry.style-override"]
    timestamp: AwareDatetime
    import_id: Identifier = Field(..., alias="importId")
    object_id: Identifier = Field(..., alias="objectId")
    style: VisualStyleOverride


class SetLayerVisibilityCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.layers.set-visibility"]
    timestamp: AwareDatetime
    object_ids: list[Identifier] = Field(..., alias="objectIds", min_length=1)
    visible: bool


class SetSelectionLockCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.selection.set-lock"]
    timestamp: AwareDatetime
    group_ids: list[Identifier] = Field(..., alias="groupIds")
    locked: bool
    object_ids: list[Identifier] = Field(..., alias="objectIds")


class SetSelectionStyleCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.selection.set-style"]
    timestamp: AwareDatetime
    object_ids: list[Identifier] = Field(..., alias="objectIds", min_length=1)
    style: VisualStyleOverride


class SetViewportCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.viewport.set"]
    timestamp: AwareDatetime
    viewport: Viewport


class TranslateGeometryImportCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.geometry.translate"]
    timestamp: AwareDatetime
    delta: Vec2
    import_id: Identifier = Field(..., alias="importId")


class UpdateTextCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.text.update"]
    timestamp: AwareDatetime
    object_id: Identifier = Field(..., alias="objectId")
    text: str = Field(..., max_length=100000)


class BoardCommandOrder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_revision_at_creation: int = Field(..., alias="baseRevisionAtCreation", ge=0)
    lamport: int = Field(..., ge=1)


class GeometryOsObjectSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    gir_entity_id: str = Field(..., alias="girEntityId", max_length=256, min_length=1)
    gir_entity_type: str = Field(..., alias="girEntityType", max_length=128, min_length=1)
    import_id: Identifier = Field(..., alias="importId")
    kind: Literal["geometryos"]


class LineObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.line"]
    end: Vec2
    line_style: LineStyle | None = Field(None, alias="lineStyle")


class ExplicitPlotSeries(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    domain: Domain
    expression: str = Field(..., max_length=2000, min_length=1)
    id: Identifier
    kind: Literal["explicit"]
    name: str = Field(..., max_length=128, min_length=1)
    style: PlotSeriesStyle
    visible: bool


class ParametricPlotSeries(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    closed: bool
    id: Identifier
    kind: Literal["parametric"]
    name: str = Field(..., max_length=128, min_length=1)
    parameter_name: Literal["t"] = Field(..., alias="parameterName")
    range: Range
    style: PlotSeriesStyle
    visible: bool
    x_expression: str = Field(..., alias="xExpression", max_length=2000, min_length=1)
    y_expression: str = Field(..., alias="yExpression", max_length=2000, min_length=1)


class RelationPlotSeries(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expression: str = Field(..., max_length=2000, min_length=1)
    fill_opacity: float = Field(..., alias="fillOpacity", ge=0.0, le=1.0)
    id: Identifier
    kind: Literal["relation"]
    name: str = Field(..., max_length=128, min_length=1)
    style: PlotSeriesStyle
    visible: bool


PlotSeries = RootModel[ExplicitPlotSeries | ParametricPlotSeries | RelationPlotSeries]


class CubicBezierSegment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    control1: Vec2
    control2: Vec2
    end: Vec2
    start: Vec2


class VectorInkSample(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    point: Vec2
    pressure: float = Field(..., ge=0.0, le=1.0)
    timestamp_ms: float = Field(..., alias="timestampMs", ge=0.0)


class RectangleObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.rectangle"]
    size: Size2


class SvgObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["svg-import.svg"]
    sanitized_svg: str = Field(..., alias="sanitizedSvg", max_length=524288, min_length=1)
    sanitizer_policy_version: Literal["tutorboard.svg-sanitizer/1"] = Field(
        ..., alias="sanitizerPolicyVersion"
    )
    size: Size1
    view_box: SvgViewBox = Field(..., alias="viewBox")


class TextObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.text"]
    text: str = Field(..., max_length=100000)


class Transform2D(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rotation: float
    scale: PositiveVec2
    translation: Vec2


class VisualOverride(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rotation: float
    scale: PositiveVec2
    style: VisualStyleOverride | None = None
    translation: Vec2


class SetGroupTransformCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.groups.set-transform"]
    timestamp: AwareDatetime
    group_id: Identifier = Field(..., alias="groupId")
    transform: Transform2D


class BoardGroup(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    locked: bool
    object_ids: list[Identifier] = Field(..., alias="objectIds", min_length=1)
    transform: Transform2D


class CoordinatePlotDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    axes: Axes
    coordinate_viewport: CoordinateViewport = Field(..., alias="coordinateViewport")
    expression_language: Literal["tutorboard-expression/1"] = Field(..., alias="expressionLanguage")
    grid: Grid
    legend: Legend
    parameters: list[PlotParameter] = Field(..., max_length=32)
    series: list[PlotSeries] = Field(..., max_length=32)
    size: Size


class CoordinatePlotObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["math.coordinate-plot"]
    definition: CoordinatePlotDefinition


class EllipseObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.ellipse"]
    radius: PositiveVec2


class EmbeddedImageObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["image.embedded"]
    content_sha256: str = Field(..., alias="contentSha256", pattern="^[a-f0-9]{64}$")
    data_url: str = Field(
        ...,
        alias="dataUrl",
        max_length=12582912,
        min_length=1,
        pattern="^data:image/(?:png|jpeg|gif|svg\\+xml);base64,[A-Za-z0-9+/=]+$",
    )
    file_name: str = Field(..., alias="fileName", max_length=256, min_length=1)
    intrinsic_size: IntrinsicSize = Field(..., alias="intrinsicSize")
    mime_type: MimeType = Field(..., alias="mimeType")
    size: Size1


class GeometryImportRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    board_object_ids: list[Identifier] = Field(..., alias="boardObjectIds", min_length=1)
    canonical_gir: Any = Field(..., alias="canonicalGir")
    created_at: AwareDatetime = Field(..., alias="createdAt")
    geometry_os_api_version: Literal["1.0.0"] = Field(..., alias="geometryOsApiVersion")
    gir_schema_version: Literal["0.2.0"] = Field(..., alias="girSchemaVersion")
    id: Identifier
    mapping: dict[str, list[Identifier]]
    prompt: str = Field(..., max_length=100000)
    raw_response: Any = Field(..., alias="rawResponse")
    request_id: str | None = Field(..., alias="requestId", pattern="^[A-Za-z0-9._:-]{1,220}$")
    root_group_id: Identifier = Field(..., alias="rootGroupId")
    visual_overrides: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        VisualOverride,
    ] = Field(..., alias="visualOverrides")
    visual_transform: Transform2D = Field(..., alias="visualTransform")


class VectorInkData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    centerline: list[CubicBezierSegment] = Field(..., max_length=100000, min_length=1)
    closed: bool
    samples: list[VectorInkSample] = Field(..., max_length=100000, min_length=2)
    version: Literal["1.0"]


class AddGroupCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.groups.add"]
    timestamp: AwareDatetime
    group: BoardGroup


class UpdateCoordinatePlotCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.coordinate-plot.update"]
    timestamp: AwareDatetime
    expected: CoordinatePlotDefinition
    object_id: Identifier = Field(..., alias="objectId")
    replacement: CoordinatePlotDefinition


class PenStrokeObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    group_id: Identifier | None = Field(..., alias="groupId")
    id: Identifier
    locked: bool
    position: Vec2
    rotation: float
    scale: PositiveVec2
    source: UserObjectSource | GeometryOsObjectSource
    style: ObjectStyle
    visible: bool
    kind: Literal["drawing.pen-stroke"]
    ink: VectorInkData
    points: list[Vec2] = Field(..., max_length=100000, min_length=2)


BoardObject = RootModel[
    PenStrokeObject
    | LineObject
    | RectangleObject
    | EllipseObject
    | TextObject
    | EmbeddedImageObject
    | SvgObject
    | CoordinatePlotObject
]


class AddObjectsCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.objects.add"]
    timestamp: AwareDatetime
    at_index: int | None = Field(None, alias="atIndex", ge=0)
    objects: list[BoardObject] = Field(..., min_length=1)


class ImportGeometryCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.geometry.import"]
    timestamp: AwareDatetime
    group: BoardGroup
    import_record: GeometryImportRecord = Field(..., alias="importRecord")
    objects: list[BoardObject] = Field(..., min_length=1)


class PasteContentCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.clipboard.paste"]
    timestamp: AwareDatetime
    geometry_imports: list[GeometryImportRecord] = Field(..., alias="geometryImports")
    groups: list[BoardGroup]
    objects: list[BoardObject]


class ReplaceObjectsCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    id: Identifier
    kind: Literal["core.objects.replace"]
    timestamp: AwareDatetime
    originals: list[BoardObject] = Field(..., min_length=1)
    replacements: list[BoardObject] = Field(..., min_length=1)


BoardCommand = RootModel[
    AddGroupCommand
    | AddObjectsCommand
    | CutContentCommand
    | DeleteObjectsCommand
    | ImportGeometryCommand
    | MoveGroupCommand
    | MoveObjectsCommand
    | MoveSelectionCommand
    | OffsetGeometryLabelCommand
    | PasteContentCommand
    | RemoveGroupsCommand
    | RenameDocumentCommand
    | ReorderLayersCommand
    | ReplaceObjectsCommand
    | SetGeometryVisualStyleCommand
    | SetGroupTransformCommand
    | SetLayerVisibilityCommand
    | SetSelectionLockCommand
    | SetSelectionStyleCommand
    | SetViewportCommand
    | TranslateGeometryImportCommand
    | UpdateCoordinatePlotCommand
    | UpdateTextCommand
]


class OrderedBoardCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    command: BoardCommand
    order: BoardCommandOrder


class BoardCommandEnvelope13(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actor_id: Identifier = Field(..., alias="actorId")
    base_revision: int = Field(..., alias="baseRevision", ge=0)
    commands: list[OrderedBoardCommand] = Field(..., max_length=100, min_length=1)
    document_id: Identifier = Field(..., alias="documentId")
    expected_document_sha256: str = Field(
        ..., alias="expectedDocumentSha256", pattern="^[a-f0-9]{64}$"
    )
    idempotency_key: str = Field(
        ..., alias="idempotencyKey", max_length=128, min_length=1, pattern="^[A-Za-z0-9._:-]+$"
    )
    schema_version: Literal["1.3"] = Field(..., alias="schemaVersion")


class BoardDocument(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        regex_engine="python-re",
    )
    created_at: AwareDatetime = Field(..., alias="createdAt")
    geometry_imports: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        GeometryImportRecord,
    ] = Field(..., alias="geometryImports")
    groups: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        BoardGroup,
    ]
    id: Identifier
    objects: dict[
        constr(
            pattern=r"^(?!(?:__proto__|constructor|prototype)$)[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"
        ),
        BoardObject,
    ]
    order: list[Identifier]
    schema_version: Literal["1.2"] = Field(..., alias="schemaVersion")
    title: str = Field(..., max_length=256, min_length=1)
    updated_at: AwareDatetime = Field(..., alias="updatedAt")
    viewport: Viewport
