from __future__ import annotations

import argparse
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_ROOT = ROOT / "schemas" / "board" / "v1"
OUTPUT_ROOT = ROOT / "src" / "tutor_assistant_web" / "shared" / "board_contracts"
SCHEMA_NAMES = (
    "board-command-envelope.schema.json",
    "board-document.schema.json",
    "board-geometry-import.schema.json",
    "board-snapshot.schema.json",
)


def _generate(output_root: Path) -> None:
    with tempfile.TemporaryDirectory(prefix=".tutor-board-contract-input-", dir=ROOT) as temporary:
        input_root = Path(temporary)
        for name in SCHEMA_NAMES:
            shutil.copy2(SCHEMA_ROOT / name, input_root / name)
        subprocess.run(
            [
                "datamodel-codegen",
                "--input",
                str(input_root),
                "--input-file-type",
                "jsonschema",
                "--output",
                str(output_root),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--target-python-version",
                "3.12",
                "--snake-case-field",
                "--use-standard-collections",
                "--use-union-operator",
                "--use-schema-description",
                "--use-title-as-name",
                "--use-root-model-type-alias",
                "--field-constraints",
                "--formatters",
                "builtin",
                "--disable-timestamp",
            ],
            check=True,
        )
        (output_root / "__init__.py").write_text(
            "# generated by datamodel-codegen:\n#   filename:  TutorBoard board/v1 schemas\n",
            encoding="utf-8",
        )
        subprocess.run(["ruff", "format", str(output_root)], check=True)
        subprocess.run(
            ["ruff", "check", "--fix", "--select", "I", str(output_root)],
            check=True,
        )
        subprocess.run(["ruff", "format", str(output_root)], check=True)


def _files(root: Path) -> dict[str, bytes]:
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file() and path.suffix != ".pyc" and "__pycache__" not in path.parts
    }


def check() -> None:
    with tempfile.TemporaryDirectory(prefix=".tutor-board-contract-output-", dir=ROOT) as temporary:
        output_root = Path(temporary) / "models"
        _generate(output_root)
        expected = _files(output_root)
        actual = _files(OUTPUT_ROOT)
        if expected != actual:
            stale = sorted(set(expected) ^ set(actual))
            changed = sorted(
                name for name in set(expected) & set(actual) if expected[name] != actual[name]
            )
            details = ", ".join(stale + changed)
            raise SystemExit(
                "Generated board contract DTOs are stale"
                f"{f': {details}' if details else ''}. "
                "Run make board-contract-generate."
            )


def generate() -> None:
    if OUTPUT_ROOT.exists():
        shutil.rmtree(OUTPUT_ROOT)
    _generate(OUTPUT_ROOT)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    if arguments.check:
        check()
    else:
        generate()


if __name__ == "__main__":
    main()
